# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-19 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=1024, unique=True)),
                ('date', models.DateField()),
                ('imdbid', models.CharField(max_length=9)),
                ('poster', models.ImageField(upload_to='')),
            ],
        ),
    ]
