# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-04 14:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_newmovienotification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newmovienotification',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='newmovienotification',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
