# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-17 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20160117_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='path',
            field=models.TextField(),
        ),
    ]
