# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-07 16:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_movierequest_user_squashed_0010_auto_20160302_2202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField()),
                ('vtt_file', models.FileField(blank=True, null=True, upload_to='subtitles')),
                ('name', models.TextField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtitles', to='application.Movie')),
            ],
        ),
        migrations.AlterModelOptions(
            name='movierequest',
            options={'ordering': ['title']},
        ),
    ]
