# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_auto_20170107_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtitle',
            name='path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
