# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-02-19 17:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion



def forwards(apps, schema_editor):
    User = apps.get_model("auth", "User")
    Profile = apps.get_model("application", "Profile")
    for user in User.objects.all():
        p = Profile.objects.create(user=user)
        p.save()

def backwards(apps, schema_editor):
    Profile = apps.get_model("application", "Profile")
    for p in Profile.objects.all():
        p.delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0011_auto_20170115_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.UUIDField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(forwards, backwards),
    ]
