# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-26 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, max_length=1024, null=True, upload_to='posters'),
        ),
    ]
